server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/honeybees/PROJ/spring/spring-config/src/main/resources/config
